FROM ruby:2.5

RUN mkdir /src
WORKDIR /src

COPY memtar.gemspec /src
COPY Gemfile /src
COPY Gemfile.lock /src
COPY lib/memtar/version.rb /src/lib/memtar/

RUN gem install bundler -v 2.1.4
RUN bundle install

COPY . /src/

CMD [ "rake", "spec" ]
