FROM ruby:3-slim

ENV BUNDLER_VERSION 2.2.18


RUN apt-get update && \
    # Pull latest OS package updates to reduce risk of vulnerable
    # packages.
    apt-get dist-upgrade -y && \
    # git is required to install some of the ruby gem dependencies
    apt-get install -y git && \
    apt-get clean

RUN mkdir /src
WORKDIR /src

COPY memtar.gemspec /src
COPY Gemfile /src
COPY Gemfile.lock /src
COPY lib/memtar/version.rb /src/lib/memtar/

RUN gem install bundler:$BUNDLER_VERSION && bundle install

COPY . /src/

CMD [ "rake", "spec" ]
